### PR TITLE
Show flash success message after saving settings

### PR DESCRIPTION
**Pull request by ramanbuttar**

### CODE REVIEW

**Comment by ramanbuttar** [comment]
@accessd can you have a look at this PR?

**Comment by accessd** [comment]
It's ok. But add tests please.

**Comment by accessd** [comment]
Implemented at https://github.com/accessd/rails-settings-ui/commit/aa2daf4fdfcfd3d3257affbeb87be251fdcd793c

**Comment by edwardmp** [comment]
Would it be an idea to post the flash message as the default :notice rather than :success which is often not implemented to display these flash messages and thus this feature goes unnoticed?

**Pull request closed without merging**
