### PR TITLE
Remove use of Fixnum in Ruby 2.4+

### PR DESCRIPTION
**Pull request by edwardmp**

### CODE REVIEW

**Comment by accessd** [comment]
Good solution! Thanks!

**Comment by edwardmp** [comment]
May I suggest testing against ruby 2.4 in Travis as well?

**Comment by accessd** [comment]
Added 2.4 in Travis

**Comment by edwardmp** [comment]
@accessd Thanks. Can you ship a new release?

**Comment by accessd** [comment]
@edwardmp done

**Pull request merged**
